### ISSUE TITLE
kmd wallet shows negative confirmations and wont display current status

### ISSUE THREAD

**Issue by Cerv4ntez** [pbca26/hw-kmd-wallet#169]
Hi, i claimed my rewards today and since then the wallet displays a wrong balance and the most recent transactions have negative confirmations
<img width="651" alt="broken_kmd" src="https://user-images.githubusercontent.com/18594385/110118485-b93b6a80-7dba-11eb-8d6f-53c31c227e2d.PNG">

**Comment by Cerv4ntez** [comment]
i did some more testing, the web wallet ist completely unfunctional at this point. i transferred all my funds out of the wallet and it still displays the status as shown in the screenshot

**Comment by pbca26** [comment]
thanks for the heads up
it should be resolved now

**Comment by Cerv4ntez** [comment]
Thanks for fixing this so quickly!

**Comment by pbca26** [comment]
closing
