### ISSUE TITLE
Back

### ISSUE THREAD

**Issue by IronFishPool** [pbca26/hw-kmd-wallet#273]
How do i get back to choose the wallet, i choose Trezor instead of Ledger, and now i'm stuck with Trezor, no back button , not even in the menu, i tried to close the app and relaunch and it's the same.

**Comment by pbca26** [comment]
Go to Settings, there's a dropdown to change preferred vendor.

**Comment by pbca26** [comment]
You can do it from the login screen or inside your wallet.

**Comment by pbca26** [comment]
closing
