### ISSUE TITLE
VOTE2022 showing only a fraction of my balance.

### ISSUE THREAD

**Issue by StrobFX** [pbca26/hw-kmd-wallet#311]
Using ledger nano x on windows. I tried desktop as well as brave and chrome.
I tried setting the discovery gap limit up to 200. I also tried setting history max length to 100.
At one point in the beginning I could see all my balance but after sending some I can see only a fraction of my balance and can't see it all no matter what settings I use.

**Comment by pbca26** [comment]
Added a few fixes for this issue
